TEST_VALUE:
  name: 'dev_cookie'
MYSQL_CONFIG:
  name: 'user-test'
  type: 'mysql'
  host: 'localhost'
  port: 3306
  username: 'root'
  password: '123456'
  database: 'test'
  entities: 'mysql'
  synchronize: true
